### ISSUE TITLE
Can't get current track data

### ISSUE THREAD

**Issue by airtoxin** [dtinth/JXA-Cookbook#11]
When iTunes plays tracks on Apple Music, wiki's script returns error.

```
var track = Application('iTunes').currentTrack()
track.name()
```

`Error on line 1: Error: Unknown object type.`

https://github.com/dtinth/JXA-Cookbook/wiki/iTunes#getting-the-current-track-an-example-of-specifier-vs-property-access

**Comment by dtinth** [comment]
Yes, it’s [broken](http://dougscripts.com/itunes/2015/07/itunes-12-2-and-applescript-issues-volume-1/). Can you [try using the selection](http://dougscripts.com/itunes/2015/06/cute-new-itunes-track-property/) instead?

```js
var track = Application('iTunes').selection()[0]
```

**Comment by airtoxin** [comment]
It returns `undefined`.

I got exact track name on Apple Music by `Application("iTunes").sources()[2].playlists()[0].tracks()[0].name();`. But It returns error when playing local tracks. hmm...

**Comment by Tatsh** [comment]
So Apple Music is unpredictable and of course undocumented. What a surprise. You could update the Wiki about Apple Music. I personally do not care for it.

In this case, most likely you have to iterate through `.sources()` for a specific property then use `.playlists()[0]` (hopefully always `0`) and then `tracks()[0]` (again hopefully always `0`, and `tracks[0]` should work too).

`.sources` can contain any kind of source (including a plugged in iPhone/iPod), so you definitely have to filter it. The Apple-provided guide shows what properties a source can have.

**Comment by airtoxin** [comment]
iTunes fixed it
