### ISSUE TITLE
Any resources on CSV manipulation?

### ISSUE THREAD

**Issue by JRHutson** [dtinth/JXA-Cookbook#14]
I'm trying to put together a workflow that will parse a CSV and merge that array with one returned from Configurator based on a common field. All the examples I've found use JQuery to do array merges. Is there a way to access JQuery functionality in JSA or is there another way to accomplish this?

**Comment by Tatsh** [comment]
There is no built-in public class or helper you can use for CSV parsing. You will have to roll your own or use a package from npm for that. As for anything jQuery does, check out the jQuery source viewer: http://james.padolsey.com/jquery/#v=git&fn=

Most of the non-web stuff jQuery does are simple 10 line or less functions, for things we hate having to type in JS over and over.

**Comment by JRHutson** [comment]
I've only dealt with JS in a browser till this, so this afternoon I finally figured out that Node.js was something I had to install locally. I'm starting to wrap my head around making this work. Thanks for the help.
