### ISSUE TITLE
NSMatrix selectCell

### ISSUE THREAD

**Issue by Slavetz** [dtinth/JXA-Cookbook#26]
I have one problem in my code below.
I am interested in matrix1.selectedCell.tag
If I change state of the 2nd cell to true it changes, but the state of the first cell is not changed to false,
and I can't select one of them.
I understand that I need to use selectCell(atRow:column:) or selectCell(withTag:) methods, but I can not understand the syntax.

Please help me to understand the syntax of selectCell(atRow:column:) or selectCell(withTag:) methods

//================ code ===================
var app = Application.currentApplication();
app.includeStandardAdditions = true;
ObjC.import("Cocoa");

var styleMask = $.NSTitledWindowMask | $.NSClosableWindowMask | $.NSMiniaturizableWindowMask;
var windowWidth = 450;
var windowHeight = 295;
var minWidth = 450;
var minHeight = 295;
var ctrlsHeight = 80;
var window = $.NSWindow.alloc.initWithContentRectStyleMaskBackingDefer(
  $.NSMakeRect(0, 0, windowWidth, windowHeight),
  styleMask,
  $.NSBackingStoreBuffered,
  false
);

var proto = $.NSButtonCell.alloc.init;
proto.title = "Options";
proto.buttonType = $.NSRadioButton;

var matrix1 = $.NSMatrix.alloc.initWithFrameModePrototypeNumberOfRowsNumberOfColumns(
	$.NSMakeRect(198, 195, 270, 20),
	$.NSRadioModeMatrix, proto, 1, 3
);

matrix1.cellSize = {width: 90, height: 20};

var m1Cells = matrix1.cells;

m1Cells.objectAtIndex(0).title = "Title 1";
m1Cells.objectAtIndex(0).tag = 1;
m1Cells.objectAtIndex(1).title = "Title 2";
m1Cells.objectAtIndex(1).tag = 2;
m1Cells.objectAtIndex(2).title = "Title 3";
m1Cells.objectAtIndex(2).tag = 3;

window.contentView.addSubview(matrix1);

window.center;
window.title = "Matrix Test";
window.makeKeyAndOrderFront(window);

matrix1.cells.objectAtIndex(1).state = true;

console.log(matrix1.selectedCell.title.js);
console.log(matrix1.selectedCell.tag);
//================ code ===================

**Comment by Tatsh** [comment]
Go on the documentation page and ensure you click on *Objective-C* near the top. Avoid the Swift code reference. You can add `?language=objc` to almost any page.

https://developer.apple.com/reference/appkit/nsmatrix/1436399-selectcellatrow?language=objc

This is just like how you called `-[NSWindow initWithContentRect:styleMask:backing:defer:]`:

```javascript
matrix1.selectCellAtRowColumn(/* int */ row, /* int */ column)
matrix1.selectCellWithTag(/* int */ tag)
```

**Comment by Slavetz** [comment]
Objective-C, of course!
All the time I was trying to guess how to write with JS Objective-C Bridge but looking SWIFT reference... *facepalm*
Thank you!
Can you recommend same more useful editor than ScriptEditor?

**Comment by Tatsh** [comment]
I'm only using Vim for JXA stuff primarily because I just keep references open and this is a little easier than coding Objective-C (or Swift) without any help like Xcode would provide. Nothing will beat the auto-completion in ScriptEditor though.

**Comment by Slavetz** [comment]
Thanks for answers
